In [1]:
import pandas as pd

In [2]:
# imnporting list of tickers from a .csv file

tickers_list = pd.read_csv('../Assignment/tickers/tickers_list.csv')
tickers_list

        NIFTY50 NIFTYNEXT50 NIFTYMIDCAP150 NIFTYSMALLCAP250 NIFTYMICROCAP250
0    ADANIPORTS         ACC        3MINDIA       AARTIDRUGS         ADFFOODS
1    APOLLOHOSP    ADANIENT            ABB          ABSLAMC              AGI
2    ASIANPAINT  ADANIGREEN         AIAENG       ADVENZYMES          ACCELYA
3      AXISBANK  ADANITRANS      APLAPOLLO        AEGISCHEM              ACE
4    BAJAJ-AUTO   AMBUJACEM         AUBANK         ALLCARGO         AHLUCONT
..          ...         ...            ...              ...              ...
245         NaN         NaN            NaN         WESTLIFE            WABAG
246         NaN         NaN            NaN       WOCKPHARMA       VALIANTORG
247         NaN         NaN            NaN       ZENSARTECH          VOLTAMP
248         NaN         NaN            NaN        ZYDUSWELL           WELENT
249         NaN         NaN            NaN           ECLERX       WSTCSTPAPR

[250 rows x 5 columns]

In [3]:
# Using random sampling to get a list 12% of the companies out of the total list of 750 companies
# i.e. a tickers list of approx. 90 companies.
# The tickers are picked from each index in proportion.

tickers = tickers_list.apply(lambda x : x.sample(frac = 0.12))

In [4]:
tickers = pd.DataFrame(tickers.unstack().dropna())
tickers

                               0
NIFTY50          14    EICHERMOT
                 16      HCLTECH
                 23    ICICIBANK
                 28    KOTAKBANK
                 32    NESTLEIND
...                          ...
NIFTYMICROCAP250 188    RELINFRA
                 200     SANSERA
                 205      SHALBY
                 208  SHOPERSTOP
                 241    USHAMART

[97 rows x 1 columns]

In [5]:
tickers = tickers.values.tolist()
tickers = [name for sub in tickers for name in sub]
tickers

['EICHERMOT',
 'HCLTECH',
 'ICICIBANK',
 'KOTAKBANK',
 'NESTLEIND',
 'RELIANCE',
 'SHREECEM',
 'TATAMOTORS',
 'AMBUJACEM',
 'BANDHANBNK',
 'HDFCAMC',
 'HAVELLS',
 'JUBLFOOD',
 'LTI',
 'MUTHOOTFIN',
 'TORNTPHARM',
 '3MINDIA',
 'AIAENG',
 'AAVAS',
 'ABCAPITAL',
 'ASHOKLEY',
 'GMRINFRA',
 'HAL',
 'INDHOTEL',
 'KAJARIACER',
 'LAURUSLABS',
 'MPHASIS',
 'NATIONALUM',
 'NAM-INDIA',
 'PETRONET',
 'PFC',
 'RELAXO',
 'STARHEALTH',
 'SUMICHEM',
 'TRIDENT',
 'UNOMINDA',
 'UNIONBANK',
 'ANURAS',
 'ASTERDM',
 'BALAMINES',
 'CAMS',
 'DCMSHRIRAM',
 'DELTACORP',
 'ELGIEQUIP',
 'GARFIBRES',
 'GESHIP',
 'GAEL',
 'GPPL',
 'HEG',
 'HATHWAY',
 'IIFL',
 'INFIBEAM',
 'JSL',
 'KNRCON',
 'MMTC',
 'MGL',
 'NESCO',
 'RBLBANK',
 'RAILTEL',
 'SIS',
 'SHILPAMED',
 'SOBHA',
 'STAR',
 'SPARC',
 'THYROCARE',
 'UFLEX',
 'VAKRANGEE',
 'AMRUTANJAN',
 'ARVINDFASN',
 'AUTOAXLES',
 'CENTRUM',
 'CRAFTSMAN',
 'DEEPAKFERT',
 'DHANUKA',
 'DOLATALGO',
 'FINOPB',
 'GTPL',
 'GRSE',
 'GEOJITFSL',
 'GREENPANEL',
 'IFCI',
 'JINDALPOLY',
 'KCP',
 'KSL',
 'KOLTEPATIL',
 'NEWGEN',
 'NUCLEUS',
 'ORISSAMINE',
 'PILANIINVS',
 'PUNJABCHEM',
 'RATEGAIN',
 'RAYMOND',
 'RELINFRA',
 'SANSERA',
 'SHALBY',
 'SHOPERSTOP',
 'USHAMART']

In [6]:
# importing yfinance library

import yfinance as yf

In [7]:
# Downloading price data using yfinance

df = []

yahoo_tickers = [name + '.NS' for name in tickers]
yahoo_tickers

# Using 'Adj Close' column of the price data as the representation for stock price
for ticker in yahoo_tickers:
    tickdwld= yf.download(ticker, start = "2015-04-01", end = "2022-04-01")
    tickdwld = tickdwld['Adj Close']
    
    df.append(tickdwld)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [8]:
df = pd.DataFrame(df)
df= df.T
df.columns = tickers
df

              EICHERMOT      HCLTECH  ...  SHOPERSTOP    USHAMART
Date                                  ...
2015-04-01  1420.335571   401.056885  ...  407.029633   22.930450
2015-04-06  1399.318115   397.305695  ...  408.466980   22.881245
2015-04-07  1417.125977   398.371368  ...  407.079132   22.586004
2015-04-08  1465.141602   408.729797  ...  404.154846   23.176485
2015-04-09  1445.427368   410.988892  ...  391.813080   23.570143
...                 ...          ...  ...         ...         ...
2022-03-25  2321.400879  1147.089722  ...  446.149994  110.223633
2022-03-28  2364.265381  1132.110962  ...  455.149994  119.523750
2022-03-29  2464.101074  1135.758423  ...  460.750000  122.722198
2022-03-30  2470.111084  1133.326660  ...  465.000000  131.825485
2022-03-31  2440.905273  1131.916504  ...  470.549988  132.366776

[1728 rows x 97 columns]

In [9]:
# Saving the tickers list and price data in '.csv' format for further analysis

tickers = pd.DataFrame(tickers)
tickers.to_csv('../Assignment/data/tickers.csv')
df.to_csv('../Assignment/data/price_data.csv')